### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by FredericoAndrade** [andrewharvey/geojson-polygon-labels#14]
Running `npm install --global geojson-polygon-labels` yields the following tracel; looks like mapnik is not behaving. Suggestions?

```
npm WARN deprecated detect-geocsv@0.1.0: This module is now under the @mapbox namespace: install @mapbox/detect-geocsv instead
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
/Users/fredericoandrade/.nvm/versions/node/v10.15.1/bin/geojson-polygon-labels -> /Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/bin/geojson-polygon-labels

> mapnik@3.7.2 install /Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
  CXX(target) Release/obj.target/mapnik/src/mapnik_logger.o
In file included from In file included from ../src/mapnik_logger.cpp../src/mapnik_logger.cpp::11:
:
In file included from In file included from ../src/utils.hpp../src/utils.hpp::77:
:
../../nan/nan.h../../nan/nan.h::839839::1818::  warning: warning: 'MakeCallback' is deprecated: 'MakeCallback'Use  isMakeCallback(...,  deprecated:async_context)
Use       [-Wdeprecated-declarations]MakeCallback(...,
async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
    return node::MakeCallback(
                 ^
/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:176:1: note/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h: :176'MakeCallback': 1has:  been
      noteexplicitly:  marked'MakeCallback'  deprecatedhas  herebeen

      explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h::9191::2020::  notenote: : expandedexpanded  fromfrom  macromacro

            'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

In file included from In file included from ../src/mapnik_logger.cpp../src/mapnik_logger.cpp::11:
:
In file included from In file included from ../src/utils.hpp../src/utils.hpp::77:
:
../../nan/nan.h../../nan/nan.h::854854::1818::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse  MakeCallback(...,MakeCallback(...,  async_context)async_context)

            [-Wdeprecated-declarations][-Wdeprecated-declarations]

    return node::MakeCallback(    return node::MakeCallback(

                 ^                 ^

/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h::169169::11::  notenote: : 'MakeCallback''MakeCallback'  hashas  beenbeen

            explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",

^^

/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h::9191::2020::  notenote: : expandedexpanded  fromfrom  macromacro

            'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator

                   ^                   ^

In file included from ../src/mapnik_logger.cpp:1In file included from :
../src/mapnik_logger.cppIn file included from :../src/utils.hpp1::
7In file included from :
../src/utils.hpp:../../nan/nan.h7::
869:../../nan/nan.h18::869 :18:warning : warning'MakeCallback':  is 'MakeCallback'deprecated:  isUse  deprecated:MakeCallback(...,  Useasync_context)
MakeCallback(...,       [-Wdeprecated-declarations]async_context)

      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^    return node::MakeCallback(

                 ^
/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:162:1/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:: 162:1note::  'MakeCallback' notehas:  been'MakeCallback'
       hasexplicitly  beenmarked
       deprecatedexplicitly  heremarked
deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:91:20/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:: 91:20note::  expanded notefrom:  macroexpanded
       from'NODE_DEPRECATED' macro

      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/mapnik_logger.cpp:1:
In file included from In file included from ../src/utils.hpp../src/mapnik_logger.cpp::71:
:
In file included from ../../nan/nan.h../src/utils.hpp::14787::
31:../../nan/nan.h :1478:warning31: : 'MakeCallback' warningis:  deprecated: 'MakeCallback'Use  isMakeCallback(...,  deprecated:async_context)
Use       [-Wdeprecated-declarations]MakeCallback(...,
async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
    return scope.Escape(node::MakeCallback(
                              ^
/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:176:1/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:: 176:1note::  'MakeCallback' notehas:  been'MakeCallback'
       hasexplicitly  beenmarked
       deprecatedexplicitly  heremarked
deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:91:20/Users/fredericoandrade/.node-gyp/10.15.1/include/node/node.h:: 91:20note::  expanded notefrom:  macroexpanded
       from'NODE_DEPRECATED' macro

      'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
    __attribute__((deprecated(message))) declarator
                   ^
../src/mapnik_logger.cpp../src/mapnik_logger.cpp::8282::2929::  warningwarning: : 'IntegerValue''IntegerValue'  isis  deprecateddeprecated  [-Wdeprecated-declarations][-Wdeprecated-declarations]

    int severity = info[0]->IntegerValue();    int severity = info[0]->IntegerValue();

                            ^                            ^

/Users/fredericoandrade/.node-gyp/10.15.1/include/node/v8.h:2476:3: /Users/fredericoandrade/.node-gyp/10.15.1/include/node/v8.hnote:: 2476:'IntegerValue'3 :has  been
note      : explicitly 'IntegerValue'marked  hasdeprecated  beenhere

explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/fredericoandrade/.node-gyp/10.15.1/include/node/v8config.h:327:29/Users/fredericoandrade/.node-gyp/10.15.1/include/node/v8config.h:: 327:29note::  expanded notefrom:  macroexpanded
       from'V8_DEPRECATED' macro

      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
  declarator __attribute__((deprecated))
                            ^
5 warnings generated.
5 warnings generated.
rm: ./Release/.deps/Release/obj.target/mapnik/src/mapnik_logger.o.d.raw: No such file or directory
make: *** [Release/obj.target/mapnik/src/mapnik_logger.o] Error 1
gyp ERR!   CXX(target) Release/obj.target/mapnik/src/node_mapnik.o
build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/fredericoandrade/.nvm/versions/node/v10.15.1/bin/node" "/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/fredericoandrade/.nvm/versions/node/v10.15.1/bin/node /Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/Users/fredericoandrade/.nvm/versions/node/v10.15.1/bin/node" "/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/fredericoandrade/.nvm/versions/node/v10.15.1/bin/node /Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding' (1)
../src/node_mapnik.cpp:5:10: fatal error: 'mapnik_vector_tile.hpp' file not foundec install script
#include "mapnik_vector_tile.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fredericoandrade/.npm/_logs/2019-04-23T20_27_46_980Z-debug.log
1 error generated.
make: *** [Release/obj.target/mapnik/src/node_mapnik.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/fredericoandrade/.nvm/versions/node/v10.15.1/bin/node" "/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/fredericoandrade/.nvm/versions/node/v10.15.1/lib/node_modules/geojson-polygon-labels/node_modules/mapnik
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok```

**Comment by andrewharvey** [comment]
We recently replaced Mapnik with geojson-stream. I just made a new release 1.3.0 which includes those changes, if you could try installing again with the latest version?

**Comment by FredericoAndrade** [comment]
Worked like a charm! Thanks a million!
